name: pkgx/brewkit/audit

inputs:
  pkg:
    description: |
      * eg. pkgx.sh@1.1
      * if unset uses `$BREWKIT_PKGSPEC`
      * if unset checks for modifications in `$PKGX_PANTRY_PATH || $PKGX_PANTRY_DIR`
    required: false
  token:
    default: ${{ github.token }}
    required: true

runs:
  using: composite
  steps:
    - name: fetch deno deps
      shell: bash
      run: |
        echo "::group::fetch deno deps"
        cd $GITHUB_ACTION_PATH
        pkgx deno^1 cache ./audit.ts
        echo "::endgroup::"

    - run: ${GITHUB_ACTION_PATH}/audit.ts '${{ inputs.pkg }}'
      shell: bash
      env:
        GITHUB_TOKEN: ${{inputs.token}}
