name: pkgx/brewkit/audit

inputs:
  pkg:
    description: |
      * eg. pkgx.sh@1.1
      * if unset uses `$BREWKIT_PKGSPEC`
      * if unset checks for modifications in `$PKGX_PANTRY_PATH`
    required: false
  token:
    default: ${{ github.token }}
    required: true

runs:
  using: composite
  steps:
    - run: |
        if ! pkgx --sync; then
          echo "::error::you must use: pkgxdev/setup before using this action"
          exit 1
        fi
      shell: bash

    - name: fetch deno deps
      shell: bash
      run: |
        echo "::group::fetch deno deps"
        tmpdir=$(mktemp -d)
        ln -s ${GITHUB_ACTION_PATH}/../bin/cmd/audit $tmpdir/audit.ts
        pkgx deno cache $tmpdir/audit.ts --config=${GITHUB_ACTION_PATH}/../deno.jsonc
        echo "::endgroup::"

    - run: ${GITHUB_ACTION_PATH}/../bin/cmd/audit '${{ inputs.pkg }}'
      shell: bash
      env:
        GITHUB_TOKEN: ${{inputs.token}}
