versions:
  - 1.0.0

build:
  - run: echo "{{prefix}}" >pc-cmake.pc
    working-directory: '{{prefix}}/lib/pkgconfig'
  - run: echo "{{prefix}}" >pc-cmake-targets.cmake
    working-directory: '{{prefix}}/lib/cmake/pc-cmake'
  # testing dollar escaping
  - |
    FOO=1
    BAR=2
    export BAZ=3
  - run:
      test $(sh $PROP) = --3
    prop: |
      echo $FOO-$BAR-$BAZ

test:
  - test "$(cat {{prefix}}/lib/pkgconfig/pc-cmake.pc)" = '${pcfiledir}/../..'
  - test "$(cat {{prefix}}/lib/cmake/pc-cmake/pc-cmake-targets.cmake)" = '${CMAKE_CURRENT_LIST_DIR}/../../..'
