name: tea/pantry/bottle
description: internal tea.xyz specific at this time

inputs:
  gpg-key-id:
    description: gpg key id
    required: true
  gpg-key-passphrase:
    description: gpg key passphrase
    required: true
  built:
    description: packages to bottle
    required: true
  compression:
    description: compression to use (gz or xz)
    required: true
outputs:
  bottles:
    description: bottle files
    value: ${{ steps.bottle.outputs.bottles }}
  checksums:
    description: checksum files
    value: ${{ steps.bottle.outputs.checksums }}
  signatures:
    description: signature files
    value: ${{ steps.bottle.outputs.signatures }}

runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/bottle.ts ${{ inputs.built }}
      id: bottle
      shell: sh
      env:
        COMPRESSION: ${{ inputs.compression }}
        GPG_KEY_ID: ${{ inputs.gpg-key-id }}
        GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}
