versions:
  github: pkgxdev/mash
  transform: |-
    v => v.includes('2') ? v : undefined

build:
  working-directory: ${{prefix}}
  script: |
    echo {{version}} > VERSION

test:
  - test $(cat {{prefix}}/VERSION) = {{version}}

  # test that cache directories are created in our sandbox
  - run: touch ~/.cache/foo
    if: linux
  - run: touch ~/Library/Caches/foo
    if: darwin