versions:
  github: ImageMagick/ImageMagick
  transform: v => v.replace('-', '.')

build:
  working-directory: ${{prefix}}
  script: |
    echo {{version}} > VERSION

test:
  test $(cat {{prefix}}/VERSION) = {{version}}
