distributable:
  - url: git+https://github.com/pkgxdev/brewkit
    ref: v{{version}}

versions:
  github: pkgxdev/brewkit

build:
  dependencies:
    git-scm.org: '*'
  script:
    - touch foo
    - git add foo
    - run:
      - mkdir -p {{prefix}}
      - mv foo {{prefix}}

test: true
