distributable:
  url: git+https://github.com/pkgxdev/brewkit
  ref: v{{version}}

versions:
  - 1.0.0

dependencies:
  python.org: ^3.11

build: |
  mv props/* .
  rmdir props
  python-venv.py {{prefix}}/bin/myapp

provides:
  - bin/myapp

test:
  - myapp

  - run: |
      test $(basename $FIXTURE .rb).rb = $(basename $FIXTURE)
      test $(cat $FIXTURE) = foo
    fixture:
      content: foo
      extname: .rb
