#!/bin/sh

if [ -x /usr/local/bin/pkgx ]; then
  # removed from PATH deliberately
  pkgx=/usr/local/bin/pkgx
else
  # probs this is running in pkgx CI/CD
  pkgx="$(ls -d ${PKGX_DIR:-$HOME/.pkgx}/pkgx.sh/v* | tail -1)/bin/pkgx"
fi

exec "$pkgx" +freedesktop.org/pkg-config pkg-config "$@"
