name: tea/brewkit/get-platform
description: Outputs the platform spec we need for builds

inputs:
  platform:
    description: >
      The platform+arch to get specs for
    required: true
  projects:
    description: >
      The projects to check for availability
    required: false
    default: ''

outputs:
  os:
    description: the OS for general tasks
    value: ${{ steps.platform.outputs.os }}
  build-os:
    description: the OS for build tasks
    value: ${{ steps.platform.outputs.build-os }}
  container:
    description: the container for build tasks
    value: ${{ steps.platform.outputs.container }}
  test-matrix:
    description: the matrix of os/containers for test tasks
    value: ${{ steps.platform.outputs.test-matrix }}
  available:
    description: which packages are available for the requested platform
    value: ${{ steps.platform.outputs.available }}

runs:
  using: composite
  steps:
    - uses: teaxyz/setup@v0
      with:
        srcroot: null

    - uses: teaxyz/brewkit/actions/cache@v0
      with:
        cache-name: get-platform

    - uses: actions/checkout@v3

    - run: ${{github.action_path}}/get-platform.ts
      shell: sh
      id: platform
      env:
        PLATFORM: ${{ inputs.platform }}
        PROJECTS: ${{ inputs.projects }}
        TEA_PANTRY_PATH: ${{ github.workspace }}
