name: +tea.xyz/brewkit
description: sets up tea, tea.xyz/brewkit & caching

# inputs and outputs are `teaxyz/setup` passthrough

inputs:
  prefix:
    description: >
      Where tea stows its packages.
      Defaults to `$HOME/.tea`.
    required: false
outputs:
  version:
    description: Your project’s version.
    value: ${{ steps.tea.outputs.version }}
  prefix:
    description: The prefix you specified.
    value: ${{ steps.tea.outputs.prefix }}

runs:
  using: composite
  steps:
    - uses: teaxyz/setup@v0
      id: tea
      with:
        prefix: ${{ inputs.prefix }}
        +: tea.xyz/brewkit^0.7.1
        # prevent pantry from reassigning TEA_PREFIX etc.
        srcroot: null

    - uses: teaxyz/brewkit/actions/cache@v0
      with:
        cache-name: setup

    - run: |
        if test -d "${{ github.workspace }}"/projects; then
          echo "TEA_PANTRY_PATH=${{ github.workspace }}" >> $GITHUB_ENV
        fi
      shell: sh
