distributable:
  url: https://github.com/pkgxdev/brewkit/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

versions:
  github: pkgxdev/brewkit

dependencies:
  zlib.net: ^1.1

build:
  - cc props/foo.c -lz
  - install -D a.out {{prefix}}/bin/foo

test: |
  test $(foo) = sup_bro
  test -z "$SRCROOT"
