distributable:
  - url: https://FAILURE.DOT.COM
  - url: https://github.com/pkgxdev/brewkit/archive/refs/tags/v{{ version }}.tar.gz
    strip-components: 1

versions:
  github: pkgxdev/brewkit

dependencies:
  zlib.net: ~1.3

build:
  - cc -Werror -Wuninitialized props/foo.c -lz
  - install -D a.out {{prefix}}/bin/foo
  - run:
      test $($PROP) = 1.3
    prop: |
      #!/bin/sh
      echo {{deps.zlib.net.version.marketing}}

test: |
  test $(foo) = sup_bro
  test -z "$SRCROOT"
