on:
  workflow_dispatch:
    inputs:
      version:
        required: true

concurrency:
  group: ${{ github.event.release.tag_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  qa:
    uses: ./.github/workflows/ci.yml
  shellcheck:
    uses: ./.github/workflows/shellcheck.yml

  publish:
    needs: [qa, shellcheck]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: teaxyz/setup@v0

      - name: determine previous version
        id: previous
        run: |
          versions="$(git tag | grep '^v[0-9]\+\.[0-9]\+\.[0-9]\+')"
          v_latest="$(npx -- semver $versions | tail -n1)"
          echo "version=$v_latest" >> $GITHUB_OUTPUT

      - name: sanity
        run:
          tea semverator lt ${{ steps.previous.outputs.version }} ${{ github.event.inputs.version }}

      - run: gh release create
          ${{ github.event.inputs.version }}
          --latest
          --generate-notes
          --notes-start-tag=${{ steps.previous.outputs.version }}
        env:
          GH_TOKEN: ${{ github.token }}

      # we need the new tag for the next step
      - run: git tag ${{ steps.strip.outputs.v }}

      - uses: fischerscode/tagger@v0
        with:
          prefix: v
          tag: ${{ steps.strip.outputs.v }}
