on:
  push:
    paths:
      - '**/*.sh'
      - 'bin/*'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@1.1.0
        with:
          severity: warning
        env:
          SHELLCHECK_OPTS: -s dash