on:
  push:
    paths:
      - '**/*.sh'
      - 'bin/*'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: teaxyz/setup@v0
      - run: tea xc shellcheck
